# Introduction To The Dataset

In [1]:
import pandas as pd

data=pd.read_csv("thanksgiving.csv",encoding="Latin-1")

In [2]:
data.head()

,RespondentID,Do you celebrate Thanksgiving?,What is typically the main dish at your Thanksgiving dinner?,What is typically the main dish at your Thanksgiving dinner? - Other (please specify),How is the main dish typically cooked?,How is the main dish typically cooked? - Other (please specify),What kind of stuffing/dressing do you typically have?,What kind of stuffing/dressing do you typically have? - Other (please specify),What type of cranberry saucedo you typically have?,What type of cranberry saucedo you typically have? - Other (please specify),...,Have you ever tried to meet up with hometown friends on Thanksgiving night?,"Have you ever attended a ""Friendsgiving?""",Will you shop any Black Friday sales on Thanksgiving Day?,Do you work in retail?,Will you employer make you work on Black Friday?,How would you describe where you live?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
0,4337954960,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,None,NaN,...,Yes,No,No,No,NaN,Suburban,18 - 29,Male,"$75,000 to $99,999",Middle Atlantic
1,4337951949,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Other (please specify),Homemade cranberry gelatin ring,...,No,No,Yes,No,NaN,Rural,18 - 29,Female,"$50,000 to $74,999",East South Central
2,4337935621,Yes,Turkey,NaN,Roasted,NaN,Rice-based,NaN,Homemade,NaN,...,Yes,Yes,Yes,No,NaN,Suburban,18 - 29,Male,"$0 to $9,999",Mountain
3,4337933040,Yes,Turkey,NaN,Baked,NaN,Bread-based,NaN,Homemade,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$200,000 and up",Pacific
4,4337931983,Yes,Tofurkey,NaN,Baked,NaN,Bread-based,NaN,Canned,NaN,...,Yes,No,No,No,NaN,Urban,30 - 44,Male,"$100,000 to $124,999",Pacific

In [3]:
print(data.columns)

Index(['RespondentID', 'Do you celebrate Thanksgiving?',
       'What is typically the main dish at your Thanksgiving dinner?',
       'What is typically the main dish at your Thanksgiving dinner? - Other (please specify)',
       'How is the main dish typically cooked?',
       'How is the main dish typically cooked? - Other (please specify)',
       'What kind of stuffing/dressing do you typically have?',
       'What kind of stuffing/dressing do you typically have? - Other (please specify)',
       'What type of cranberry saucedo you typically have?',
       'What type of cranberry saucedo you typically have? - Other (please specify)',
       'Do you typically have gravy?',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Brussel sprouts',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Carrots',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Cauliflower',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Corn',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Cornbread',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Fruit salad',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Green beans/green bean casserole',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Macaroni and cheese',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Mashed potatoes',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Rolls/biscuits',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Squash',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Vegetable salad',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Yams/sweet potato casserole',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify)',
       'Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify).1',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Buttermilk',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Cherry',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Chocolate',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Coconut cream',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Key lime',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Peach',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Sweet Potato',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - None',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify)',
       'Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify).1',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Apple cobbler',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Blondies',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Brownies',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Carrot cake',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Cheesecake',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Cookies',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Fudge',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Ice cream',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Peach cobbler',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - None',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Other (please specify)',
       'Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Other (please specify).1',
       'Do you typically pray before or after the Thanksgiving meal?',
       'How far will you travel for Thanksgiving?',
       'Will you watch any of the following programs on Thanksgiving? Please select all that apply. - Macy's Parade',
       'What's the age cutoff at your "kids' table" at Thanksgiving?',
       'Have you ever tried to meet up with hometown friends on Thanksgiving night?',
       'Have you ever attended a "Friendsgiving?"',
       'Will you shop any Black Friday sales on Thanksgiving Day?',
       'Do you work in retail?',
       'Will you employer make you work on Black Friday?',
       'How would you describe where you live?', 'Age', 'What is your gender?',
       'How much total combined money did all members of your HOUSEHOLD earn last year?',
       'US Region'],
      dtype='object')

# Filtering Out Rows From A DataFrame

In [4]:
data["Do you celebrate Thanksgiving?"].value_counts(dropna = False)

Yes    980
No      78
Name: Do you celebrate Thanksgiving?, dtype: int64

In [5]:
data=data[data["Do you celebrate Thanksgiving?"]=="Yes"]

#  Using Value_counts To Explore Main Dishes

In [6]:
data["What is typically the main dish at your Thanksgiving dinner?"].value_counts(dropna = False)

Turkey                    859
Other (please specify)     35
Ham/Pork                   29
Tofurkey                   20
Chicken                    12
Roast beef                 11
NaN                         6
I don't know                5
Turducken                   3
Name: What is typically the main dish at your Thanksgiving dinner?, dtype: int64

In [7]:
data[data["What is typically the main dish at your Thanksgiving dinner?"] == "Tofurkey"]["Do you typically have gravy?"]

4      Yes
33     Yes
69      No
72      No
77     Yes
145    Yes
175    Yes
218     No
243    Yes
275     No
393    Yes
399    Yes
571    Yes
594    Yes
628     No
774     No
820     No
837    Yes
860     No
953    Yes
Name: Do you typically have gravy?, dtype: object

# Figuring Out What Pies People Eat

In [8]:
apple = "Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple"
pumpkin = "Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin"
pecan = "Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan"

(data[apple].notnull() | data[pumpkin].notnull() | data[pecan].notnull()).value_counts()

True     876
False    104
dtype: int64

# Findings
1. 876 people eat atleast one of the three pies
2. 104 people eat none of the pies

# Converting Age To Numeric

In [9]:
data["Age"].value_counts(dropna = False)

45 - 59    269
60+        258
30 - 44    235
18 - 29    185
NaN         33
Name: Age, dtype: int64

In [10]:
def extract_age(age_str):
    if pd.isnull(age_str):
        return None
    age_str = age_str.split(" ")[0]
    age_str = age_str.replace("+", "")
    return int(age_str)

data["int_age"] = data["Age"].apply(extract_age)

In [11]:
data["int_age"].describe()

count    947.000000
mean      40.089757
std       15.352014
min       18.000000
25%       30.000000
50%       45.000000
75%       60.000000
max       60.000000
Name: int_age, dtype: float64

# Findings

Although we only have a rough approximation of age, and it skews downward because we took the first value in each string (the lower bound), we can see that that age groups of respondents are fairly evenly distributed.

# Converting Income To Numeric

In [12]:
data["How much total combined money did all members of your HOUSEHOLD earn last year?"].value_counts(dropna = False)

$25,000 to $49,999      166
$75,000 to $99,999      127
$50,000 to $74,999      127
Prefer not to answer    118
$100,000 to $124,999    109
$200,000 and up          76
$10,000 to $24,999       60
$0 to $9,999             52
$125,000 to $149,999     48
$150,000 to $174,999     38
NaN                      33
$175,000 to $199,999     26
Name: How much total combined money did all members of your HOUSEHOLD earn last year?, dtype: int64

In [13]:
def extract_income(income_str):
    if pd.isnull(income_str) or "Prefer" in income_str :
        return None
    income_str=income_str.split(" ")[0]
    income_str=income_str.replace("$","")
    income_str=income_str.replace(",","")
    return int(income_str)
    
data["int_income"]=data["How much total combined money did all members of your HOUSEHOLD earn last year?"].apply(extract_income)

In [14]:
data["int_income"].describe()

count       829.000000
mean      75965.018094
std       59068.636748
min           0.000000
25%       25000.000000
50%       75000.000000
75%      100000.000000
max      200000.000000
Name: int_income, dtype: float64

# Findings
Although we only have a rough approximation of income, and it skews downward because we took the first value in each string (the lower bound), the average income seems to be fairly high, although there is also a large standard deviation.

# Correlating Travel Distance And Income

In [15]:
data[data["int_income"]<50000]["How far will you travel for Thanksgiving?"].value_counts()

Thanksgiving is happening at my home--I won't travel at all                         106
Thanksgiving is local--it will take place in the town I live in                      92
Thanksgiving is out of town but not too far--it's a drive of a few hours or less     64
Thanksgiving is out of town and far away--I have to drive several hours or fly       16
Name: How far will you travel for Thanksgiving?, dtype: int64

In [16]:
data[data["int_income"]>150000]["How far will you travel for Thanksgiving?"].value_counts()

Thanksgiving is happening at my home--I won't travel at all                         49
Thanksgiving is local--it will take place in the town I live in                     25
Thanksgiving is out of town but not too far--it's a drive of a few hours or less    16
Thanksgiving is out of town and far away--I have to drive several hours or fly      12
Name: How far will you travel for Thanksgiving?, dtype: int64

# Findings
It appears that more people with high income have Thanksgiving at home than people with low income. This may be because younger students, who don't have a high income, tend to go home, whereas parents, who have higher incomes, don't.

# Linking Friendship And Age

In [17]:
data.pivot_table(index="Have you ever tried to meet up with hometown friends on Thanksgiving night?"
                 ,columns='Have you ever attended a "Friendsgiving?"',values="int_age")

Have you ever attended a "Friendsgiving?"                  No        Yes
Have you ever tried to meet up with hometown fr...
No                                                  42.283702  37.010526
Yes                                                 41.475410  33.976744

In [18]:
data.pivot_table(index="Have you ever tried to meet up with hometown friends on Thanksgiving night?"
                 ,columns='Have you ever attended a "Friendsgiving?"',values="int_income")

Have you ever attended a "Friendsgiving?"                     No           Yes
Have you ever tried to meet up with hometown fr...
No                                                  78914.549654  72894.736842
Yes                                                 78750.000000  66019.736842

# Findings
It appears that people who are younger are more likely to attend a Friendsgiving, and try to meet up with friends on Thanksgiving.

# Calculating Number Of People Working on Thanksgiving

In [19]:
data['Will you employer make you work on Black Friday?'].value_counts(dropna = False)

NaN              910
Yes               43
No                20
Doesn't apply      7
Name: Will you employer make you work on Black Friday?, dtype: int64

# Finding Regional Patterns in Dinner Menus

In [20]:
data.pivot_table(index = ['What is typically the main dish at your Thanksgiving dinner?','US Region'])

                                                                       RespondentID  \
What is typically the main dish at your Thanksg... US Region
Chicken                                            Middle Atlantic     4.336661e+09
                                                   Mountain            4.336382e+09
                                                   New England         4.336066e+09
                                                   South Atlantic      4.336358e+09
                                                   West North Central  4.336352e+09
                                                   West South Central  4.336209e+09
Ham/Pork                                           East North Central  4.336902e+09
                                                   East South Central  4.336910e+09
                                                   Middle Atlantic     4.336872e+09
                                                   Mountain            4.336759e+09
                                                   Pacific             4.336555e+09
                                                   South Atlantic      4.336672e+09
                                                   West North Central  4.336739e+09
                                                   West South Central  4.337632e+09
I don't know                                       Pacific             4.336162e+09
                                                   West North Central  4.336084e+09
Other (please specify)                             East North Central  4.336889e+09
                                                   East South Central  4.337105e+09
                                                   Middle Atlantic     4.336572e+09
                                                   New England         4.337188e+09
                                                   Pacific             4.336706e+09
                                                   South Atlantic      4.336698e+09
                                                   West North Central  4.336682e+09
                                                   West South Central  4.336934e+09
Roast beef                                         East South Central  4.337424e+09
                                                   Middle Atlantic     4.336073e+09
                                                   Pacific             4.335958e+09
                                                   South Atlantic      4.336449e+09
Tofurkey                                           East North Central  4.337490e+09
                                                   Middle Atlantic     4.336841e+09
                                                   Mountain            4.336740e+09
                                                   New England         4.336895e+09
                                                   Pacific             4.336958e+09
                                                   South Atlantic      4.336899e+09
                                                   West North Central  4.336658e+09
                                                   West South Central  4.337372e+09
Turducken                                          Middle Atlantic     4.336739e+09
                                                   Pacific             4.337475e+09
Turkey                                             East North Central  4.336802e+09
                                                   East South Central  4.336830e+09
                                                   Middle Atlantic     4.336824e+09
                                                   Mountain            4.336782e+09
                                                   New England         4.336825e+09
                                                   Pacific             4.336465e+09
                                                   South Atlantic      4.336798e+09
                                                   West North Central  4.336808e+09
                                                   West South Central  4.336648e+09

                                                                         int_age  \
What is typically the main dish at your Thanksg... US Region
Chicken                                            Middle Atlantic     60.000000
                                                   Mountain            60.000000
                                                   New England         45.000000
                                                   South Atlantic      50.000000
                                                   West North Central  18.000000
                                                   West South Central  18.000000
Ham/Pork                                           East North Central  34.500000
                                                   East South Central  60.000000
                                                   Middle Atlantic     30.000000
                                                   Mountain            30.000000
                                                   Pacific             33.000000
                                                   South Atlantic      30.857143
                                                   West North Central  34.500000
                                                   West South Central  24.000000
I don't know                                       Pacific             18.000000
                                                   West North Central  18.000000
Other (please specify)                             East North Central  45.000000
                                                   East South Central  41.250000
                                                   Middle Atlantic     52.500000
                                                   New England         30.000000
                                                   Pacific             40.333333
                                                   South Atlantic      45.000000
                                                   West North Central  50.000000
                                                   West South Central  31.000000
Roast beef                                         East South Central  45.000000
                                                   Middle Atlantic     52.500000
                                                   Pacific             45.000000
                                                   South Atlantic      50.000000
Tofurkey                                           East North Central  30.000000
                                                   Middle Atlantic     39.000000
                                                   Mountain            37.500000
                                                   New England         18.000000
                                                   Pacific             24.000000
                                                   South Atlantic      46.000000
                                                   West North Central  24.000000
                                                   West South Central  24.000000
Turducken                                          Middle Atlantic     30.000000
                                                   Pacific             45.000000
Turkey                                             East North Central  41.777778
                                                   East South Central  44.160000
                                                   Middle Atlantic     40.061538
                                                   Mountain            41.513514
                                                   New England         41.058824
                                                   Pacific             39.644860
                                                   South Atlantic      41.386740
                                                   West North Central  38.100000
                                                   West South Central  37.168831

                                                                          int_income
What is typically the main dish at your Thanksg... US Region
Chicken                                            Middle Atlantic     200000.000000
                                                   Mountain                      NaN
                                                   New England          62500.000000
                                                   South Atlantic       15000.000000
                                                   West North Central            NaN
                                                   West South Central       0.000000
Ham/Pork                                           East North Central   62500.000000
                                                   East South Central   75000.000000
                                                   Middle Atlantic     105000.000000
                                                   Mountain             50000.000000
                                                   Pacific              28333.333333
                                                   South Atlantic       60000.000000
                                                   West North Central   75000.000000
                                                   West South Central  137500.000000
I don't know                                       Pacific              50000.000000
                                                   West North Central            NaN
Other (please specify)                             East North Central  150000.000000
                                                   East South Central   71250.000000
                                                   Middle Atlantic      41666.666667
                                                   New England          75000.000000
                                                   Pacific              97500.000000
                                                   South Atlantic       51666.666667
                                                   West North Central   41666.666667
                                                   West South Central   66666.666667
Roast beef                                         East South Central  150000.000000
                                                   Middle Atlantic      50000.000000
                                                   Pacific              10000.000000
                                                   South Atlantic       37500.000000
Tofurkey                                           East North Central            NaN
                                                   Middle Atlantic      70000.000000
                                                   Mountain            137500.000000
                                                   New England          25000.000000
                                                   Pacific              45000.000000
                                                   South Atlantic      112500.000000
                                                   West North Central   50000.000000
                                                   West South Central   67500.000000
Turducken                                          Middle Atlantic               NaN
                                                   Pacific             200000.000000
Turkey                                             East North Central   71557.377049
                                                   East South Central   69148.936170
                                                   Middle Atlantic      91725.663717
                                                   Mountain             85806.451613
                                                   New England          90125.000000
                                                   Pacific              73865.979381
                                                   South Atlantic       72866.242038
                                                   West North Central   68500.000000
                                                   West South Central   79338.235294

# Exploring main dishes by locality

In [21]:
pd.crosstab(data['How would you describe where you live?'], 
            data['What is typically the main dish at your Thanksgiving dinner?'])

What is typically the main dish at your Thanksgiving dinner?,Chicken,Ham/Pork,I don't know,Other (please specify),Roast beef,Tofurkey,Turducken,Turkey
How would you describe where you live?,,,,,,,,
Rural,2,7,3,9,1,3,2,189
Suburban,3,17,1,13,3,9,1,449
Urban,7,4,0,13,6,8,0,198